name: kyobodts_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  flutter_inappwebview: 6.1.5
  shared_preferences: 2.3.2
  url_launcher: 6.3.1
  flutter_launcher_icons: 0.14.1
  flutter_native_splash: 2.4.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.1
  path_provider: ^2.1.4
  provider: ^6.1.2
  http: ^1.2.2
  flutter_widget_from_html: ^0.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/html/
    - assets/icon/